### ISSUE TITLE
Feature request: Slight background for inline code blocks

### ISSUE THREAD

**Issue by Akeboshiwind** [7368697661/Origami#15]
I use inline code blocks a lot and have found it difficult to differentiate them.
As a work around I've added the following as a css snippet:

```css
.cm-s-obsidian span.cm-inline-code  {
    background-color: rgba(255, 255, 255, 0.07) !important;
}
```

Which changes this:
<img width="336" alt="Screen Shot 2023-02-12 at 11 55 39" src="https://user-images.githubusercontent.com/8889986/218309490-93637a9f-1ace-48d8-8adf-86b1a4f763a7.png">

Into this:
<img width="336" alt="Screen Shot 2023-02-12 at 11 54 19" src="https://user-images.githubusercontent.com/8889986/218309426-9644a951-6dee-45b8-af8f-0561465f2005.png">

Not sure if you want to integrate this, but I thought I would let you know!
