### ISSUE TITLE
3-digit line numbers

### ISSUE THREAD

**Issue by DutchPete** [7368697661/Origami#3]
The 1<sup>st</sup> digit of a 3-digit line number is cut off.

So, e.g. line number 158 is shown as 58.

Edit:
from the console I have come up with this:
```css
.cm-lineNumbers .cm-gutterElement {
  padding-left: 0 !important;
}
```

That shows the 3 digit alright, but the number, whether 1, 2 or 3 digits longs, is awfully close to the text.
